spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: mistral
      embedding:
        model: mistral
    vectorstore:
      type: simple  # Force in-memory store

server:
  port: 8080