spring:
  ai:
    ollama:
      enabled: true
      base-url: http://localhost:11434
      chat:
        model: mistral
      embedding:
        model: mistral-embed
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080